---

- name: Ensure the PGP key is installed
  apt_key: id=AC40B2F7 state=present url="http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x561F9B9CAC40B2F7"

- name: Ensure https support for apt is installed
  apt: pkg=apt-transport-https state=present

- name: Ensure the passenger apt repository is added
  apt_repository: state=present repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger precise main'

- name: Ensure packages are installed
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - nginx-full
    - nginx-extras
    - passenger

  # We do this to avoid mucking around attempting to edit the main nginx.conf
- name: Install Passenger Nginx.conf
  template: src='nginx.conf.j2' dest='/etc/nginx/conf.d/passenger.conf'
  notify: restart nginx

- name: Ensure nginx is running
  service: name=nginx state=started
