---

- name: Create Groups
  group: name={{ item.1 }} state=present
  with_subelements:
    - users
    - groups

- name: Create Users
  user: name={{ item.name }} uid={{ item.uid }} home={{ item.home }} shell={{ item.shell }} comment="{{ item.comment }}" group={{ item.group }} groups={{ ",".join(item.groups) }} append={{ item.append }}
  with_items: users

