#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

export DEBUG=false
SCRIPT_PATH=$(dirname ${BASH_SOURCE})

source $SCRIPT_PATH/env

if [ ! -d $GOLLUM_PATH ];
then
  echo "Creating Wiki Datastore"
  mkdir $GOLLUM_PATH
  cd $GOLLUM_PATH
  git --bare init
  git config user.name "Anonymous Coward"
  git config user.email "anonymouscoward@mailinator.com"
fi

echo "Datastore available at:"
echo "ssh://$OPENSHIFT_APP_UUID@$OPENSHIFT_APP_DNS/~/${GOLLUM_PATH##$OPENSHIFT_HOMEDIR}"
