#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

export

cd $BARE_REPO
git config user.name "Anonymous Coward"
git config user.email "anonymouscoward@mailinator.com"
## to set the Git user we need to manually edit the config file. Using 'git config user.name "John Doe" does not work
#echo "[user]" >> config
#echo "        name = Anonymous Coward" >> config
#echo "        email = anonymouscoward@mailinator.com" >> config
