#!/bin/bash

if [[ ! -z $DEBUG ]] && $DEBUG
then

  echo
  echo
  echo "DEBUG Enabled, Outputing ENV information"
  echo
  echo

  export

  echo
  echo "debug HOOK_PATH=$(dirname ${BASH_SOURCE}) "
  echo
fi

