---

- name: Add nginx.org key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: Add nginx.org repo
  apt_repository: repo='deb http://nginx.org/packages/ubuntu/ precise nginx' state=present
  notify: update apt-cache

#- name: Halt Existing Nginx
  #service: name=nginx state=stopped

#- name: Remove Old Nginx
  #apt: package=nginx state=absent

- name: Install Nginx Full
  apt: package=nginx-full state=present
  notify: restart nginx

- name: Install Nginx.conf Customisations
  template: src='nginx.conf.j2' dest='/etc/nginx/conf.d/nginx.conf'

- name: Start nginx
  service: name=nginx state=started

- name: Delete existing default.conf (and back it up)
  file: path=/etc/nginx/conf.d/default.conf state=absent backup=yes
